const steps=[
  {count:'01 / 04',kicker:'01 · LE BESOIN',title:'Une pièce attendue pour remettre une cuisine en service.',body:'Votre client attend de pouvoir planifier son intervention. Vous avez besoin d’une date et d’un suivi fiables.',result:'Ce qui compte : connaître l’enjeu derrière le colis.',bee:'« Une pièce doit remettre une installation en service. Je garde le besoin client en vue. »'},
  {count:'02 / 04',kicker:'02 · L’IMPRÉVU',title:'La pièce arrive aux États-Unis, puis reste bloquée en douane.',body:'L’écart apparaît avant la livraison attendue. Votre équipe doit comprendre la cause et l’impact sur le délai.',result:'Ce qui compte : détecter le changement et son effet pour votre client.',bee:'« Le trajet a changé. Je signale l’écart et les informations qui manquent pour décider. »'},
  {count:'03 / 04',kicker:'03 · L’ACTION',title:'Les personnes concernées se coordonnent.',body:'Le fournisseur, le transporteur et le service client partagent le même contexte pour décider de la suite et informer le destinataire.',result:'Ce qui compte : transformer une alerte en action claire.',bee:'« Je garde tout le monde aligné sur la prochaine action et le nouveau délai. »'},
  {count:'04 / 04',kicker:'04 · LE GAIN CLIENT',title:'La réception est confirmée. Votre client peut agir.',body:'La pièce est disponible pour le service technique. Votre équipe sait que l’envoi est arrivé et peut clôturer le suivi.',result:'Du temps pour agir · un client informé · une relation préservée.',bee:'« Je confirme la réception : votre client peut organiser son intervention. »'}
];
const tabs=[...document.querySelectorAll('.step-tab')],panel=document.querySelector('#step-panel'),count=document.querySelector('#step-count'),message=document.querySelector('#bee-message'),progress=document.querySelector('.demo-progress span');
function selectStep(index,focus=false){const step=steps[index];if(!step)return;tabs.forEach((tab,i)=>{const active=i===index;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});panel.innerHTML=`<span class="demo-kicker">${step.kicker}</span><h3>${step.title}</h3><p>${step.body}</p><span class="demo-result">${step.result}</span>`;count.textContent=step.count;message.textContent=step.bee;progress.style.width=`${(index+1)*25}%`;if(focus)tabs[index].focus()}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectStep(i));tab.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;selectStep(next,true)}})});
const toggle=document.querySelector('.menu-toggle'),menu=document.querySelector('#mobile-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu');menu.hidden=!open});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Ouvrir le menu')}));window.addEventListener('resize',()=>{if(window.innerWidth>860){menu.hidden=true;toggle.setAttribute('aria-expanded','false')}});document.querySelector('#year').textContent=new Date().getFullYear();
